### ISSUE TITLE
组件能随消息面板宽度自适应

### ISSUE THREAD

**Issue by asynchat** [antvis/GPT-Vis#34]
LLM回复可能是先Markdown语法块，然后一些简要的说明，说明可长可短，消息块变宽之前，语法块已经渲染了，变宽后，组件不能自适应，加了百分比宽度也不行，只有在下一次组件更新时才会触发宽度调整，是否有解决方案或者需要另行增设功能?

预期希望是这样， 始终能与下面文字保持同宽：

<img width="1126" alt="image" src="https://github.com/user-attachments/assets/07935cb9-372c-4d1a-a67c-e73517328b0c">

**Comment by lvisei** [comment]
@asynchat 

在用的时候确实需要，根据平台聊天界面宽度调整，不设置默认宽高度都是 300 px，可能不好看！
```
.gpt-vis {
  	min-width: 600px;
  	height: 400px;
}
```

你这里想要根据上下文的情况适配宽度，应该需要写一下自适应逻辑。

另外，你这里用的 flex 布局吗？

**Comment by asynchat** [comment]
@lvisei 可以了

只设置了宽高，忘记加 flex
`<GPTVis className="w-full h-full">{message.content}</GPTVis>`
加上之后，第一次会按正常300px渲染，过一下会自动自适应宽度
`<GPTVis className="flex-col space-y-4 w-full h-full">{message.content}</GPTVis>`

谢谢

**Comment by asynchat** [comment]
@lvisei 可以了

只设置了宽高，忘记加 flex
`<GPTVis className="w-full h-full">{message.content}</GPTVis>`
加上之后，第一次会按正常300px渲染，过一下会自动自适应宽度
`<GPTVis className="flex-col space-y-4 w-full h-full">{message.content}</GPTVis>`

谢谢
